<?php
// This file generated by Propel 1.7.1 convert-conf target
// from XML runtime conf file /home/chrispenny/cookies.flyingllama.co.nz/application/build/data/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'ci' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=mysql.chrispenny.co.nz;dbname=db_baskets',
        'user' => 'chrispenny',
        'password' => 'david194264632',
      ),
    ),
    'default' => 'ci',
  ),
  'generator_version' => '1.7.1',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-ci-conf.php');
return $conf;